# 02.03 Vectors and Matrices

- dot product of two vectors. 
- matrix multiplication and dimensionality
- element wise multiplication with a "scalar" and a vector


In [2]:
import numpy as np

#### --> 1. Create Vectors
* Make a vector (1d array) of 1 to 5 using np.arange
* Make another vector (1d array) of 2,4,6,8,10 using np.linspace
* print each vector

**Double Click Here for answer**
<!--
a1 = np.arange(1,6)
a2 = np.linspace(2,10,5)
print("a1 is: ", a1)
print("a2 is: ", a2)
-->


In [3]:
a1 = np.arange(1,6)
a2 = np.linspace(2,10,5)
print("a1 is: ", a1)
print("a2 is: ", a2)

a1 is:  [1 2 3 4 5]
a2 is:  [ 2.  4.  6.  8. 10.]


### Elementwise multiplication
The * operator does elementwise multiplication.  

*Note that Octave uses .* for elementwise multiplication.*

#### --> 2. Check this out by multiplying your two vectors.


In [4]:
a1 * a2

array([ 2.,  8., 18., 32., 50.])

### Dot product
The dot product, or matrix multiplication, multiplies two matrices together.

The dot product is the sum of the products of each corresponding element.  Very useful if you have a sum of products in math notation!  E.g. when you see:

$$\sum_{i=1}^{100} x_i * y_i $$

You should think "Vectorize!"

*The dot function works like Octave *  (dot product / matrix multiplication)*

#### --> 3.  Try dot product.
> try np.dot( yourarray1,  yourarray2)   
    
> try  yourarray1  @  yourarray2 - the @ operator is the same as np.dot
    
**Double Click Here for answer**
<!--
print(np.dot(a1,a2))
print(a1 @ a2)
-->



In [6]:
print(np.dot(a1, a2))  # with np.dot
print( a1 @ a2 )  # with @

110.0
110.0


## Matrix Multiplication

Dot product and matrix multiplication are the same as long as you view dot product as multiplying a 1xn vector with a nx1 vector (i.e. you may need to transpose).

But NumPy handles that transpose for you if you should try that.

#### --> 4.  Multiply matrices

* Make a1 that's 1 by 4 with the np.arange function
* Make a2 that's  4 by 2 of counts, using the np.array constructor: [[1,2],[3,4],[5,6],[7,8]]
* Multiply a1 and a2 using the @ operator.

The inner dimensions must match.  The result is the outer dimensions...

You should get a 1x2 that's `[50, 60]`

**Double Click Here for answer**
<!--
a1 = np.arange(1,5)
a2 = np.array( [[1,2],[3,4],[5,6],[7,8]] )
a1 @ a2
-->


In [14]:
a1 = np.arange(1,5)
a2 = np.array([[1,2],[3,4],[5,6],[7,8]])
a1 @ a2


array([50, 60])



What kind of error do you get if you try to multiply mismatched matrices?  Give it a try by swapping the order of a1 and a2.

#### --> 5. Try / Except to catch error in NumPy
See if you can use a try / except block to catch the right kind of error.

```

try:
    . . . 
    something
    . . .
except *Exception Type*  as e:
    . . .
    handle the errror
    print("Error in dimensions " + str(e))
```

**Double Click Here for answer**
<!--
print('a2 is ', a2.shape, ' but a1 is ', a1.shape)

try:
    result = a2 @ a1
except ValueError as e:
    result = None
    print("Error in dimensions \n" + str(e))
-->




In [17]:
print('a2 is ', a2.shape, ' but a1 is ', a1.shape)

try: 
    a2 * a1
except ValueError as e:
    
    print("error in dimensions " + str(e))

a2 is  (4, 2)  but a1 is  (4,)
error in dimensions operands could not be broadcast together with shapes (4,2) (4,) 


# Using Dot Product and Multiplication

Let's walk through an actual example with data, so you can see how to use matrix multiplication usefully to do something practical.

This is an important example because it illustrates the singularly most important concept of all of mathematics.  Dude.  Really?  Yes.  That concept is **abstraction** - the ability to encapsulate meaning in symbols, and then figure out a way to work with those symbols with symbol tools.  And then take the results back to get new meaning.

Dude.

### The problem - Fruit ###
Bananas, apples, and pears are sold at 0.25 cents,  0.80 cents, and 0.60 cents each.  50 people are going to each buy different amounts.    How much does each person spend?

> Abstraction step.  Let's represent what each person spends as a vector. So `[1,3,4]` would mean one banana, 3 apples, 4 pears.

#### --> 6. Create an array, `orders` , of random orders for 50 people.  A 50x3 array.  Also create the prices array, a 1x3 array.

Let's suppose someone may order between 0 and 4 of each fruit. Up to but not including 5.

```
orders = ???
prices = ???

```

**Double Click Here for answer**
<!--
###

# Randomize orders for 50 people
orders = np.random.randint( 5, size=(50,3) )

#Let's set the prices…
prices = np.array( [0.25, 0.80, 0.60] )
-->



In [47]:
orders = np.random.randint(0, 4, (50,3))
prices = np.array([0.25, 0.80, 0.60])


How much does each person spend?

Note that with NumPy Arrays, as you can see, you use `[row, colunn]` to get at a value in there rather than the Python List way of `somelist[row][column]`


#### --> 7. Iterative solution

Naive way first.  Write a for loop to step through the people, and multiply each person's orders by the prices, to get an amount for each person.

*You'll need to initialize the amounts to zero.
*You'll need a for loop to step over each `person` with `range(len(amount))`  or you can also use `range(len(orders))`
*You'll need to calcualte `amount[person]` by multiplying the amount of bananas, `orders[person,0]` with the price of bananas `prices[0]`


**Double Click Here for answer**
<!--
amount = np.zeros(50)
for person in range(len(amount)):
    amount[person] = orders[person,0] * prices[0] + \
                     orders[person,1] * prices[1] +  \
                     orders[person,2] * prices[2]

-->



In [38]:
len(orders)
personSpent = np.zeros(len(orders))
for person in range(len(orders)):
    totalPerPerson = 0
    for fruit in range(len(prices)):
        spentOnFruit = orders[person, fruit] * prices[fruit]
        totalPerPerson = totalPerPerson + spentOnFruit
    personSpent[person] = totalPerPerson
print(personSpent[0:5])

[2.5  2.3  1.45 0.85 1.1 ]


In [40]:
# your code here.

# Look I made a cute little table printer.  You can define functions in JN.
# IMPORTANT:  Observe how I can slice out the top 5 rows, with the columns.
#  Challenge:  parameterize this function. So that orders and amount are paramters you pass in.
#  Extra Challenge:  Make the parameterization include the fruit names, 
#     and not even dependent on the number of fruits.
def printAmounts():
    print("Person...\t  1 2 3 4 5")
    print("Num Bananas: \t", orders[0:5,0])
    print("Num Apples:  \t", orders[0:5,1])
    print("Num Pears:   \t", orders[0:5,2])

    print("Amounts: \t",amount[0:5])

printAmounts()

Person...	  1 2 3 4 5
Num Bananas: 	 [2 2 1 1 2]
Num Apples:  	 [1 0 0 0 0]
Num Pears:   	 [2 3 2 1 1]


NameError: name 'amount' is not defined


Hold on.  Each inner assignment looks like a dot product, to me.

#### --> 8. Replace the inside of the for loop above with a dot product between `orders[person]` and `prices`

**Double Click Here for answer**
<!--
amount = np.zeros(50)
for person in range(len(amount)):
    amount[person] = orders[person] @ prices
-->



In [50]:
def fruity(myOrder, amount):
    personSpent = np.zeros(len(myOrder))
    for person in range(len(myOrder)):
        totalPerPerson = 0
        for fruit in range(len(amount)):
            spentOnFruit = myOrder @ amount
    return spentOnFruit
        
    
# Look I used my function from above!  You can define and use functions in JN.
#printAmounts()
# Do you get the same thing as before?
printFruity(orders, prices)

[3.15 0.5  2.85 3.5  3.05]


### But wait!

But then ... we can use matrix multiplicaton for the whole thing.

#### --> 9.  Vectorized solution.

* Write a single line of code to compute all of the amounts using matrix multiplication.
* Write a print statement to print the dimensions of orders and dimensions of the prices tables.

The dimensionality analysis is super critical.

**Double Click Here for answer**
<!--
amount = orders @ prices
print("orders is", orders.shape, " Prices is ", prices.shape, " amount result is", amount.shape)
printAmounts()
-->


In [29]:

printAmounts()

Person...	  1 2 3 4 5
Num Bananas: 	 [1 3 3 2 1]
Num Apples:  	 [2 3 0 0 4]
Num Pears:   	 [3 2 4 3 2]
Amounts: 	 [3.65 4.35 3.15 2.3  4.65]
Shape of orders: (50, 3) And of prices: (3,)
orders is 50x3.  Prices is 3x1.  Result is 50x1.
Person...	  1 2 3 4 5
Num Bananas: 	 [1 3 3 2 1]
Num Apples:  	 [2 3 0 0 4]
Num Pears:   	 [3 2 4 3 2]
Amounts: 	 [3.65 4.35 3.15 2.3  4.65]


## NumPy Sum

Now we can sum up the amounts spent by each person, and on each type of fruit.  Note that `np.sum(amount)` is the same as using the `sum` method of the `amount` NumPy Instance:  `amount.sum()`

By default, `sum` iterates over the rows.  That's called the **axis** of the sum.  So if you have a 50x3 array of orders, summing over the orders with axis 0 (summing rows) will give you a 1x3 result.  You can specify an axis of 1 and sum over columns, which would give you a 50x1 result.  What would that represent in this case?  

#### --> 10.  Summing by rows and columns

Part 1:
* Change the code below to use `amount.sum()` instead of `np.sum(amount...)`
* Calculate a new variable `totalCounts` to get the total number of each kind of fruit.
* Use a list comprehension of format strings to print the number of each fruit above.

**Double Click Here for answer**
<!--
# Using amount.sum instead of np.sum(amount) ... note axis=0 is optional.  0 is the default.
print(f"Total spent: {amount.sum(axis=0):0.2f}")

totalCounts = np.sum(orders, axis=0) 
print(totalCounts, "bananas, appples, pears")

-->


In [45]:
print(f"Total spent: {np.sum(amount):0.2f}")




Total spent: 173.15
Total spent: 173.15
First 5 people ate:  [6, 8, 7, 5, 7]  Fruits.
[107 102 108] bananas, appples, pears
[26.75 81.6  64.8 ] total spent on bananas, apples, pears
bananas: $26.75, apples: $81.60, pears: $64.80


Part 2:
* Calculate a new variable `totalFruitsPerPerson` to sum the total number of fruits each person ate. Use axis 1.  Print the first 5 with a list comprehension and a slice of `totalFruitsPerPerson`
* Use elementwise multiplication to get the total spent on each type of fruit, `fruitTotals`
* Print the `fruitTotals` result.

**Double Click Here for answer**
<!--
totalFruitsPerPerson = orders.sum(axis=1)
print( "First 5 people ate: ", [x for x in totalFruitsPerPerson[0:5]], " Fruits.")

fruitTotals = totalCounts * prices
print(fruitTotals, 'total spent on bananas, apples, pears')
# super fancy way:
print( ", ".join(map( lambda x,y : f"{x}: ${y:0.2f}", ['bananas', 'apples', 'pears'], fruitTotals)) )

-->

(50, 3)